#!/usr/bin/env php
<?php
/**
* 
*/
include_once 'app/libraries/DynamicRoutes.php';

$DynamicRoutes = new DynamicRoutes([
	'BASEPATH' => realpath('system'), //required from console
	'APPPATH' => realpath('application'), //required from console
	'type_file' => 'json' //can be php or json
]);

$DynamicRoutes->extendsFile( BASEPATH . '/core/Controller.php')
		->extendsFile( APPPATH . '/core/MY_Controller.php'); //not required

$DynamicRoutes->compile(true);
