#!/usr/bin/env php
<?php
/**
* 
*/
include_once 'app/libraries/DynamicRoutes.php';

$DynamicRoutes = new DynamicRoutes([
	'BASEPATH' => realpath('system'), //required from console
	'APPPATH' => realpath('application'), //required from console
	'format' => 'json' //can be php or json
]);

$help = isset($_SERVER['argv'][1]) ? $_SERVER['argv'][1] : false;

if(in_array($help, ["h","help"]))
{
	$DynamicRoutes->help();
}
else
{
	$DynamicRoutes->extendsFile( BASEPATH . '/core/Controller.php')
		->extendsFile( APPPATH . '/core/MY_Controller.php'); //not required

	$DynamicRoutes->compile(true);

}
